services:
  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "host.docker.internal:8080"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - 4040:4040
